-- USER SQL
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER "OWNER_EP1_EQUIPO_08" IDENTIFIED BY "Owner01$EP1"
DEFAULT TABLESPACE "SYSAUX"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "OWNER_EP1_EQUIPO_08" QUOTA UNLIMITED ON "SYSAUX";
ALTER USER "OWNER_EP1_EQUIPO_08" QUOTA UNLIMITED ON "USERS";

-- ROLES
ALTER USER "OWNER_EP1_EQUIPO_08" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT GRANT ANY OBJECT PRIVILEGE TO "OWNER_EP1_EQUIPO_08" ;
GRANT CREATE ANY SQL PROFILE TO "OWNER_EP1_EQUIPO_08" ;
GRANT CREATE PROFILE TO "OWNER_EP1_EQUIPO_08" ;
GRANT GRANT ANY PRIVILEGE TO "OWNER_EP1_EQUIPO_08" ;
GRANT CREATE ANY VIEW TO "OWNER_EP1_EQUIPO_08" ;
GRANT CREATE ANY TRIGGER TO "OWNER_EP1_EQUIPO_08" ;
GRANT CREATE ANY TABLE TO "OWNER_EP1_EQUIPO_08" ;
GRANT CREATE ANY TYPE TO "OWNER_EP1_EQUIPO_08" ;
GRANT GRANT ANY ROLE TO "OWNER_EP1_EQUIPO_08" ;
