-- SCRIPT 02 TABLAS Y RESTRICCIONES

-- TABLA CLIENTES

CREATE TABLE CLIENTES_EP1_EQUIPO_08 (
    id_cliente NUMBER(10) CONSTRAINT PK_CLIENTES_EP1_EQUIPO_08
        PRIMARY KEY,

    nombre VARCHAR2(100) CONSTRAINT NN_CLIENTE_NOMBRE_EP1_EQUIPO_08
        NOT NULL,

    email VARCHAR2(150) CONSTRAINT NN_CLIENTE_EMAIL_EP1_EQUIPO_08
        NOT NULL,

    CONSTRAINT UK_CLIENTE_EMAIL_EP1_EQUIPO_08
        UNIQUE (email)
);


-- TABLA PEDIDOS

CREATE TABLE PEDIDOS_EP1_EQUIPO_08 (
    id_pedido NUMBER(10) CONSTRAINT PK_PEDIDOS_EP1_EQUIPO_08
        PRIMARY KEY,

    id_cliente NUMBER(10) CONSTRAINT NN_PEDIDO_CLIENTE_EP1_EQUIPO_08
        NOT NULL,

    fecha DATE CONSTRAINT NN_PEDIDO_FECHA_EP1_EQUIPO_08
        NOT NULL,

    total NUMBER(12,2) CONSTRAINT NN_PEDIDO_TOTAL_EP1_EQUIPO_08
        NOT NULL,

    CONSTRAINT CK_PEDIDO_TOTAL_EP1_EQUIPO_08
        CHECK (total >= 0),

    CONSTRAINT FK_PEDIDO_CLIENTE_EP1_EQUIPO_08
        FOREIGN KEY (id_cliente)
        REFERENCES CLIENTES_EP1_EQUIPO_08(id_cliente)
);

-- TABLA PAGOS

CREATE TABLE PAGOS_EP1_EQUIPO_08 (
    id_pago NUMBER(10) CONSTRAINT PK_PAGOS_EP1_EQUIPO_08
        PRIMARY KEY,

    id_pedido NUMBER(10) CONSTRAINT NN_PAGO_PEDIDO_EP1_EQUIPO_08
        NOT NULL,

    monto NUMBER(12,2) CONSTRAINT NN_PAGO_MONTO_EP1_EQUIPO_08
        NOT NULL,

    fecha DATE CONSTRAINT NN_PAGO_FECHA_EP1_EQUIPO_08
        NOT NULL,

    CONSTRAINT CK_PAGO_MONTO_EP1_EQUIPO_08
        CHECK (monto > 0),

    CONSTRAINT FK_PAGO_PEDIDO_EP1_EQUIPO_08
        FOREIGN KEY (id_pedido)
        REFERENCES PEDIDOS_EP1_EQUIPO_08(id_pedido)
);