-- SCRIPT 05 ROLES Y USUARIOS
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- ROLES

CREATE ROLE ROL_READ_EP1_EQUIPO_08;

CREATE ROLE ROL_WRITE_EP1_EQUIPO_08;

CREATE ROLE ROL_AUDIT_EP1_EQUIPO_08;


-- USUARIOS

CREATE USER APP_ADMIN_EP1_EQUIPO_08
IDENTIFIED BY "Admin01$EP1";

CREATE USER APP_USER_1_EP1_EQUIPO_08
IDENTIFIED BY "User01$EP1";

CREATE USER APP_USER_2_EP1_EQUIPO_08
IDENTIFIED BY "User02$EP1";

CREATE USER AUDITOR_EP1_EQUIPO_08
IDENTIFIED BY "Audit01$EP1";


-- PERMISO DE CONEXIÓN

GRANT CREATE SESSION
TO APP_ADMIN_EP1_EQUIPO_08;

GRANT CREATE SESSION
TO APP_USER_1_EP1_EQUIPO_08;

GRANT CREATE SESSION
TO APP_USER_2_EP1_EQUIPO_08;

GRANT CREATE SESSION
TO AUDITOR_EP1_EQUIPO_08;