-- SCRIPT 06: PRIVILEGIOS

-- ROL DE SOLO LECTURA

GRANT SELECT ON OWNER_EP1_EQUIPO_08.CLIENTES_EP1_EQUIPO_08
TO ROL_READ_EP1_EQUIPO_08;

GRANT SELECT ON OWNER_EP1_EQUIPO_08.PEDIDOS_EP1_EQUIPO_08
TO ROL_READ_EP1_EQUIPO_08;

GRANT SELECT ON OWNER_EP1_EQUIPO_08.PAGOS_EP1_EQUIPO_08
TO ROL_READ_EP1_EQUIPO_08;

GRANT SELECT ON OWNER_EP1_EQUIPO_08.VW_RESUMEN_PEDIDOS_EP1_EQUIPO_08
TO ROL_READ_EP1_EQUIPO_08;


-- ROL DE ESCRITURA CONTROLADA

GRANT SELECT ON OWNER_EP1_EQUIPO_08.CLIENTES_EP1_EQUIPO_08
TO ROL_WRITE_EP1_EQUIPO_08;

GRANT SELECT ON OWNER_EP1_EQUIPO_08.PEDIDOS_EP1_EQUIPO_08
TO ROL_WRITE_EP1_EQUIPO_08;

GRANT INSERT, UPDATE
ON OWNER_EP1_EQUIPO_08.PEDIDOS_EP1_EQUIPO_08
TO ROL_WRITE_EP1_EQUIPO_08;

GRANT SELECT ON OWNER_EP1_EQUIPO_08.PAGOS_EP1_EQUIPO_08
TO ROL_WRITE_EP1_EQUIPO_08;

GRANT INSERT, UPDATE
ON OWNER_EP1_EQUIPO_08.PAGOS_EP1_EQUIPO_08
TO ROL_WRITE_EP1_EQUIPO_08;

GRANT SELECT
ON OWNER_EP1_EQUIPO_08.VW_RESUMEN_PEDIDOS_EP1_EQUIPO_08
TO ROL_WRITE_EP1_EQUIPO_08;


-- ROL DE AUDITORÍA

GRANT SELECT
ON OWNER_EP1_EQUIPO_08.CLIENTES_EP1_EQUIPO_08
TO ROL_AUDIT_EP1_EQUIPO_08;

GRANT SELECT
ON OWNER_EP1_EQUIPO_08.PEDIDOS_EP1_EQUIPO_08
TO ROL_AUDIT_EP1_EQUIPO_08;

GRANT SELECT
ON OWNER_EP1_EQUIPO_08.PAGOS_EP1_EQUIPO_08
TO ROL_AUDIT_EP1_EQUIPO_08;

GRANT SELECT
ON OWNER_EP1_EQUIPO_08.VW_RESUMEN_PEDIDOS_EP1_EQUIPO_08
TO ROL_AUDIT_EP1_EQUIPO_08;


-- ASIGNACIÓN DE ROLES

GRANT ROL_READ_EP1_EQUIPO_08
TO APP_USER_1_EP1_EQUIPO_08;

GRANT ROL_WRITE_EP1_EQUIPO_08
TO APP_USER_2_EP1_EQUIPO_08;

GRANT ROL_AUDIT_EP1_EQUIPO_08
TO AUDITOR_EP1_EQUIPO_08;


-- APP_ADMIN

GRANT SELECT, INSERT, UPDATE, DELETE
ON OWNER_EP1_EQUIPO_08.CLIENTES_EP1_EQUIPO_08
TO APP_ADMIN_EP1_EQUIPO_08;

GRANT SELECT, INSERT, UPDATE, DELETE
ON OWNER_EP1_EQUIPO_08.PEDIDOS_EP1_EQUIPO_08
TO APP_ADMIN_EP1_EQUIPO_08;

GRANT SELECT, INSERT, UPDATE, DELETE
ON OWNER_EP1_EQUIPO_08.PAGOS_EP1_EQUIPO_08
TO APP_ADMIN_EP1_EQUIPO_08;

GRANT SELECT
ON OWNER_EP1_EQUIPO_08.VW_RESUMEN_PEDIDOS_EP1_EQUIPO_08
TO APP_ADMIN_EP1_EQUIPO_08;