-- SCRIPT 07: SEGURIDAD Y AUDITORIA

-- PERFIL DE SEGURIDAD
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE PROFILE PROFILE_EP1_EQUIPO_08 LIMIT

    FAILED_LOGIN_ATTEMPTS 5

    PASSWORD_LIFE_TIME 90

    PASSWORD_REUSE_TIME 365

    PASSWORD_REUSE_MAX 5

    PASSWORD_LOCK_TIME 1

    PASSWORD_GRACE_TIME 7;
    
-- DAR PERFIL A USUARIOS

ALTER USER APP_ADMIN_EP1_EQUIPO_08
PROFILE PROFILE_EP1_EQUIPO_08;

ALTER USER APP_USER_1_EP1_EQUIPO_08
PROFILE PROFILE_EP1_EQUIPO_08;

ALTER USER APP_USER_2_EP1_EQUIPO_08
PROFILE PROFILE_EP1_EQUIPO_08;

ALTER USER AUDITOR_EP1_EQUIPO_08
PROFILE PROFILE_EP1_EQUIPO_08;